name: alpha_import_utility
description: "Sony α カメラの SD カードから未取り込みの写真・動画を自動で取り込むアプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  # Flutter 3.35 系に固定する
  # Flutter 3.38 系は Windows において、マルチバイト文字の含まれるフォルダパスに
  # インストールすると即座にクラッシュする致命的なバグがある
  sdk: ">=3.9.2 <3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  disks_desktop: ^1.0.1
  exif_reader: ^4.0.2
  file_picker: ^10.3.8
  http: ^1.2.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.0
  random_access_source: ^4.2.1
  url_launcher: ^6.3.1
  window_manager: ^0.5.1
  xml: ^6.5.0
  xxh3: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # アセット
  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
